# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "youtube"
    name       = "YouTube"
    url        = "https://www.youtube.com/@visitkarma"

    [social.params]
        icon = "brand-youtube"
